"""Версия алгоритма поиска вина (findwine pipeline).

Формат: MAJOR.MINOR.PATCH (semver-like, старт с 0.x.x).
Инкремент — по правилам в .cursor\rules\algorithm-version.mdc.
"""

# x.x.x — текущая версия пайплайна сравнения / распознавания
ALGORITHM_VERSION = "0.97.1"

# ISO-8601 local timestamp последнего изменения алгоритма (обновлять вместе с VERSION)
ALGORITHM_UPDATED_AT = "2026-09-27T22:10:00+03:00"

ALGORITHM_NOTES = (
    "0.97.1: foreign_mask — main=selected crop; primary=bottle of selected "
    "(not max-area); skip self-label and cuts >35% of crop (scan 2743 "
    "blank fill); "
    "0.97.0: bottle+label primary — prefer bottle with strongest body label "
    "(conf≥0.55 and gap≥0.20 over area-primary's best); reject low-conf "
    "full-height silhouette labels; weak largest label yields to smaller "
    "high-conf next (scan 2729 Мезыбь); "
    "0.96.1: empty_ocr_cosine_threshold default 0.75→0.86 — empty OCR match "
    "only if max cos ≥ threshold (setting in scanner Gates); "
    "0.96.0: reuse candidate — XGB compares query OCR↔previous search OCR "
    "(not catalog label); card/popup show previous OCR + badge; "
    "0.95.0: reuse_previous_searches — nearest past search among those with "
    "winner (manual_wines_id or matched/hist), skip empty-winner neighbors; "
    "0.94.0: reuse top-20 — each hit search_photos_id (0=catalog, >0=past "
    "search); allow duplicate wine via catalog+search_photos; live Google "
    "Vision skipped when reuse supplies that search's GV OCR; "
    "0.93.0: analogs always (site) — if matched, similar wines from catalog "
    "fields of winner (source=matched_wine_catalog, exclude winner); "
    "else OCR-criteria analogs as before; show_search_details setting "
    "(admin UI only); "
    "0.92.0: reuse_previous_searches — nearest past siglip2 search_photo "
    "embedding (cos≥0.5) injects that search's winner into top-19+1 and "
    "returns its Google Vision OCR; "
    "0.91.0: settings compute_hsv (default off) — skip HSV compute/gates; "
    "compute_color_delta (default on) — dominant Lab CIEDE2000 ColorDelta "
    "on candidate/winner cards; "
    "0.90.0: dead-XGB — Soft TF-IDF (fin2) всегда, даже если fin2 выключен "
    "в text_match_methods; compute_fin2 forced when final=xgb; "
    "_scores_for_method(fin1|fin2) не берёт pack чужого final_by_ocr; "
    "0.89.0: exclusive grape/winery check — multi-word forms use first word "
    "only (Цитронный Магарача→Цитронный, Абрау-Дюрсо→Абрау); "
    "0.88.0: XGB abs_v14 FEATURE 1.4.0 + siglip_cosine; train id>=800 "
    "(no exclude-listed-photos); TextScore uses embedding rank signal; "
    "0.87.2: OCR letter/digit/token replacements → ocr_homoglyphs.json "
    "(latin_to_cyrillic, digit_to_letter, token_aliases mepro→мерло); "
    "0.87.1: OCR Latin→Cyrillic homoglyphs — add L→Л, R→Р "
    "(MERLO→мерло; mixed-script tokens too); "
    "0.87.0: exclusive grape/winery on query — order by catalog frequency "
    "(wine row counts at lexicon load), first hit only; tie-break by form length; "
    "0.86.0: exclusive winery on query — match forms longest-first, stop after "
    "first hit (FANAGORIA wins over ESSE substring of NOBLESSE); "
    "0.85.0: foreign cut — disable triangles; rect-mask foreign∩selected when "
    "foreign not fully inside main and area(foreign∩main)/area(main)≤0.20; "
    "0.84.1: foreign cut — flip hypotenuse to bottle silhouette prior "
    "(left: top-left→bottom-right; right: mirror); keep |slant| from edge fit; "
    "0.84.0: foreign label cut — triangle along main-label boundary slant "
    "inside foreign∩selected (YOLO edge + |dI/dx| fit); from bottom of "
    "foreign upward if foreign is upper on primary bottle, else from top "
    "downward; magenta tri + cyan boundary on _crops; "
    "0.83.0: label_crop — mask foreign-bottle YOLO labels inside selected "
    "box as one side-wedge triangle (outer full edge of inter → apex mid "
    "inner edge; fill=median of crop center); magenta outline on _crops; "
    "status.label_crop.foreign_mask; "
    "0.82.0: dead-XGB fallback — if final=xgb and max xgb_score among "
    "exclusive survivors < xgb_dead_max (default τ=0.15), pick Soft TF-IDF "
    "fin2 match else max cosine ≥ empty_ocr_cosine_threshold (sources "
    "xgb_dead_fin2 / xgb_dead_cosine); setting + UI stepper; "
    "0.81.0: exclusive on all top-N candidates (drop XGB>0.1 gate that "
    "skipped checks when XGB weak); category/type exact match only "
    "(no spaced/translit — dry→дри in голодриги); no bare substring form "
    "hit; XGB_fin below-similar zeroing unchanged (tune via thresholds); "
    "0.80.1: fix findwine crash — exclusive XGB gate loop shadowed SearchPhoto "
    "row with score dict → AttributeError on _save_status; "
    "0.80.0: settings exclusive_use_translit + exclusive_match_spaced "
    "(grape/winery only); UI checkboxes in scanner; "
    "0.79.0: winery lexicon — strip fixed stopwords only "
    "(винодельня/winery/chateau/…); no cross-form shared-token purge "
    "(brands Denisov/Abrau/Inkerman kept); "
    "0.78.0: analogs — if OCR criteria empty or no catalog hits, fallback "
    "top-10 by cosine among embedding candidates (also when OCR empty); "
    "0.77.0: exclusive lexicon after XGB — only candidates with XGB>0.1 & "
    "XGB_fin>0 & cos>0.5; regex form compile cache; "
    "0.76.0: OCR Latin homoglyphs — S→Б (KASEPHE→каберне); with digit-in-word "
    "(PO3E→розе, 6→б) in normalize_compare_text; "
    "0.75.1: XGB model abs_v13_excl — retrain without eval/queries "
    "photos (xgb_exclude_photos / --exclude-listed-photos); v1.3 features; "
    "thr≈0.27; "
    "0.75.0: winery lexicon load — strip every token that appears in >1 "
    "unique winery/producer row (винодельня, winery, семейная, chateau… "
    "and shared brand aliases); empty/short forms dropped; "
    "0.74.0: exclusive lexicon — form match also tries RU↔LAT transliteration "
    "(денисов ↔ denisov) both ways in query OCR and catalog label text; "
    "0.73.1: openai_txt — prompt returns probabilities for ALL candidate ids "
    "(not top-5); UI sort button LLM txt on embedding candidate rows; "
    "0.73.0: text match «OpenAI сравнение текста» (openai_txt) — prompt "
    "template openai_txt_match_prompt.txt; id→prob vs catalog labels "
    "of exclusive-lexicon survivors; timeline openai_txt_match; card LLM txt; "
    "0.72.0: XGB text features v1.3 — OCR↔wines.label only (no CMS "
    "name/winery/grape/region/category features); color/type from label_ocr "
    "+ words in label text; model abs_v13; "
    "0.71.0: OCR digit-in-word → letter (PO3E→розе): 0→о 2|3→з 4→ч "
    "5→с 6→б 7→т 8→в; only when digit adjacent to letters; skip years/"
    "decimals/%/digit-heavy tokens; before latin→cyrillic homoglyphs; "
    "0.70.2: winery lexicon — strip word «винодельня» from all forms at load "
    "(collapse spaces + trim) before match/compile; "
    "0.70.1: exclusive lexicon + label-text hard_reject — string compares "
    "always on lowercased normalize (no mixed-case haystack); "
    "0.70.0: exclusive lexicon forms match with 0–2 spaces/hyphens between "
    "letters (красный ≈ «кра с  ны й») in query OCR and catalog label; "
    "XGB always scored even on hard reject — real xgb_score kept; "
    "xgb_fin=0 on reject, xgb_fin_pre_reject = fin without reject (UI gray); "
    "0.69.1: XGB after hard_reject only (exclusive∪HSV∪label_text); "
    "survivors get abs text features v1.2 (label_ocr color/type/vintage); "
    "rejected → xgb_score=0 without model call; "
    "0.69.0: XGB text features v1.2 — absolute OCR↔label only "
    "(no cosine/rel_*/hard_reject/HSV in model); color/type from "
    "label_ocr; vintage_year + year_match_recency (not foundation); "
    "homoglyphs via normalize_compare_text; model abs_v12; "
    "0.68.2: bottle_orient writes *_orient.jpg (work unchanged for UI); "
    "re-run YOLO on oriented frame; _crops shows oriented+boxes only; "
    "label/OCR/embed use oriented image; "
    "0.68.1: bottle_orient — Hough angle via length histogram peak "
    "(not median); down-weight center label décor / boost side silhouette "
    "so diagonal label stripes (e.g. Nik Weis) do not cancel real tilt; "
    "0.68.0: bottle_orient step after YOLO — upright work image by bottle "
    "axis (Canny+Hough near-vertical lines, PCA fallback); rotate before "
    "label_crop/OCR/embed; timeline bar «orient»; settings use_bottle_orient "
    "+ bottle_orient_min_deg (default 8°); "
    "0.67.0: exclusive winery lexicon — also load unique label_ocr.producer "
    "(Google categorised OCR) alongside wines.winery for Latin producer names; "
    "0.66.0: OCR Latin→Cyrillic visual homoglyphs in normalize_compare_text "
    "(mixed script tokens + pure-Latin all-homoglyph tokens like CYXOE→сухое); "
    "exclusive lexicon / XGB / CrEnc / soft text all see fixed forms; "
    "0.65.0: label-text hard_reject — no shared OCR↔catalog tokens; "
    "OCR text & catalog label empty; OCR empty & catalog has text → "
    "xgb_score=0 + hard_reject (empty-OCR cosine also skips rejects); "
    "0.64.2: fix normalize EXIF double-rotate — OpenCV 5 auto-orients JPEG; "
    "decode with IMREAD_IGNORE_ORIENTATION then apply Orientation once "
    "(phone portrait was saved as landscape work.jpg); "
    "0.64.1: analogs sort — after score, by category then type in exclusive_lexicon.json "
    "order (red→white→rose→orange; brut→…→sweet); adjacent type uses lexicon index; "
    "0.64.0: status.analogs — top-10 analog wines when no match (site only, "
    "skipped for eval=1); criteria from query OCR: winery / category (colour) / "
    "type (sweetness) / grapes via exclusive_lexicon canons + catalog-learned "
    "Latin→Cyrillic aliases; score = Σw·s / Σw_found (winery .35, grape .30, "
    "category .20, type .15), adjacent sweetness 0.4, unknown type 0.5, "
    "colour conflict ×0.75, tie-break by cosine; "
    "in-memory catalog loaded at startup; analogs ms outside timings total; "
    "0.63.2: HF SigLIP2 — requests.Session keep-alive + warm; "
    "normalize.hf_embed JPEG short-side 384 for GPU payload; "
    "0.63.1: HF SigLIP2 pause/HTTP 400 → resume в daemon без wait, сразу CPU fallback; "
    "0.63.0: SigLIP2 fallback GPU→remote CPU→in-process local (transformers, not Docker); "
    "timeline bars embed_siglip2_gpu / _cpu / _local; "
    "0.62.0: remove key-field F1 entirely (text_key_f1 step, xgb_f1/crenc_f1, OCR card F1); "
    "0.61.0: exclusive grape/winery — fuzzy form match vs catalog label (±1 letter and/or 1 substitution per token, edit≤2) for Vision OCR typos; category/type stay exact; "
    "0.60.4: OCR искомого = final_ocr_resolved only (no text_aggregated concat); text_norm follows primary engine, not merge; "
    "0.60.3: no same-URL retries for OpenAI/embed; if OpenAI or Gemini OCR fails and Google Vision is off in settings — one Vision fallback; "
    "0.60.2: OpenAI OCR retries on SSL/EOF/connection/5xx (same class as embed); "
    "0.60.1: CPU embed retries re-send image bytes (fix handle EOF → empty image); "
    "0.60.0: XGB model dir from env XGB_MODEL_DIR "
    "(default models/xgboost_text_matcher_synthetic_40_60); "
    "0.59.0: bottle+label keeps bottles with conf > bottle_min_conf (default 0.60) "
    "when several bottles are detected; exclusive grape/winery hard-reject matches "
    "the form on the catalog label text only (grape_variety/winery columns do not count); "
    "0.58.0: exclusive grape lexicon also loads label_ocr.cupage/coupage "
    "(comma/bullet-split); candidate grape blob = label + grape_variety + cupage; "
    "same form-presence hard-reject as other exclusive dictionaries; "
    "0.57.0: settings use_hsv_hard_reject + hsv_hard_reject_max (default 0.90) — "
    "absolute HSV hard reject that ignores hsv_ignore_high_cosine bypass; "
    "0.56.0: settings final_ocr (auto|engine) — which OCR text drives exclusive/"
    "XGB/CrEnc and primary decision channel; status.steps.final_by_ocr + "
    "candidate.final_by_ocr = per-OCR final for selected text method "
    "(fin1|fin2|xgb|crenc); cards/winner/sort Fin|XGB_fin|CrEnc_fin per OCR; "
    "0.55.0: settings hsv_ignore_high_cosine + hsv_ignore_cosine_min — "
    "if HSV distance > threshold but max cosine ≥ min, do not hard-reject; "
    "0.54.0: bottle+label primary — prefer label on largest bottle "
    "(≤10% outside contour, body band not neck); else crop bottle body "
    "without top price-tags; side-bottle labels do not win over primary "
    "fallback; "
    "0.53.0: HSV distance uses wines.hsv from enrich select when present; "
    "compute from crop only if missing, then persist to wines.hsv; "
    "0.52.0: settings Score — use_hsv_filter + hsv_bhattacharyya_max; "
    "when enabled, candidates with HSV Bhattacharyya > threshold are "
    "hard-rejected (unsuitable, same path as exclusive); "
    "0.51.0: HSV Bhattacharyya of query label vs top-20 crops right after "
    "cosine top-20; distance on cards and status.steps.hsv; winner distance "
    "in search_photos.hsv; "
    "0.50.1: fix findwine crash — decision match-band loop shadowed SearchPhoto "
    "row with score dict → AttributeError on _save_status; "
    "0.50.0: exclusive — if OCR hits a lexicon form (category/type/grape/winery), "
    "the same form must appear on the candidate (label + card fields); "
    "removed foreign_canon check (no longer reject for other values in the "
    "same dictionary); type now requires form presence like the rest; "
    "0.49.0: XGB/CrEnc as TextScore; XGB_fin/CrEnc_fin = w_ocr×TextScore + "
    "w_emb×Cosine on match|similar bands (same mix as fin1); below similar "
    "→ fin=0; winner only from match band by *_fin; thresholds from "
    "text_match_thresholds (not model metrics.json); "
    "0.48.0: findwine query eval (default 0); eval=1 promotes top-1 as "
    "matched_wine when the match band is empty so /v1/eval/predict can "
    "return the winner slug; "
    "0.47.1: fix findwine crash — decision xgb/crenc shadowed SearchPhoto row "
    "→ AttributeError on _save_status (scan incomplete, no matched_wine); "
    "0.47.0: text-match thresholds match/similar per method; Final score radio; "
    "similar-band → dashed cards, final empty; empty OCR skips text match, "
    "final by max cosine ≥ empty_ocr_cosine_threshold; "
    "0.46.2: bottle+label — ignore orphan labels (conf≤0.5 and ≤50% area "
    "inside any bottle) when other labels sit in bottle contours; "
    "0.46.1: bottle+label merge — all labels on a bottle (≥2, overlap ≥85%), "
    "no 2–3 cap (scan 887: 4 strips on Myskhako); "
    "0.46.0: YOLO bottle+label — dual model warmup, settings yolo_variant "
    "label|bottle_label; merge labels overlapping same bottle ≥85% "
    "(label-area) into one crop box; crops overlay shows bottles (coef=) "
    "+ all labels; "
    "0.45.0: exclusive presence requires the same lexicon form (blanc≠белое), "
    "not just the same canon; type still foreign-canon only; "
    "0.44.0: Cross Encoder (local|server) mutually exclusive; server → "
    "api_cross_encoder_matcher; timeline CrossEncoder loc/Srv; "
    "0.43.2: exclusive category/type lexicon → exclusive_lexicon.json; "
    "0.43.1: fix findwine crash — F1 loop shadowed SearchPhoto row → 500 on save; "
    "0.43.0: settings embed_cpu_use_cache → use_cache=1 on CPU SigLIP2/DINOv3; "
    "0.42.0: exclusive category/winery/grape — query canon must appear in the "
    "candidate label text (not only the DB column); type stays foreign-canon only; "
    "0.41.1: XGB/CrEnc timings are each model's own runtime (not the shared "
    "parallel wait); key F1 computed once; CrossEncoder warmed at startup; "
    "0.41.0: CrossEncoder text match (CrEnc / CrEnc_fin / key F1); "
    "settings text_match_methods + final_score_method pick matched_wine; "
    "unchecked methods are not scored; "
    "0.40.3: exclusive_lexicon hard-reject also zeros Soft FinalScore2 / best_final2 "
    "(scan 827: red query must not match white via fin2); "
    "0.40.2: XGB key-field F1 (winery/name/color/type/grape) on candidate cards "
    "(xgb_f1 + sort F1 XGB); "
    "0.40.1: label text compare — lowercase, collapse multi-spaces, trim "
    "(normalize_compare_text for OCR/soft/XGB/UI); "
    "0.40.0: XGBoost OCR↔label step (xgb_match) after top-20 embedding, "
    "parallel with exclusive; XGB / XGB_fin on cards; "
    "0.39.1: YOLO label pick — conf_gap 0.03→0.9; if next-by-size ≤½ area of "
    "largest, always keep largest; "
    "0.39.0: exclusive winery lexicon (mutual exclusion) loaded at startup; "
    "0.38.0: exclusive grape check — OCR grape from catalog lexicon must appear "
    "on candidate label/grape_variety (lexicon loaded at backend startup); "
    "0.37.2: restore exclusive_lexicon step in findwine (hard-reject before OCR score); "
    "0.37.1: exclusive category synonyms blanc→white, rouge→red; "
    "0.37.0: Soft TF-IDF (txt2/fin2) Yandex+GV + soft veto; matched_wine only fin1/fin2 "
    "(no embedding top-1 fallback); "
    "0.36.0: restore label_lines majority block (>3 lines, >50% unmatched → hard reject); "
    "0.26.0: per-OCR F1 on key fields + Score/F1 on candidate cards; "
    "0.25.3: work JPEG ≤1MB budget; "
    "0.25.2: magic-bytes save ext"
)
